#!/bin/bash

restfile="$HOME/.config/setbg"
file="$1"

if [ "${file}" = "-r" ] || [ "${file}" = "--restore" ]; then
    sh "${restfile}"
    exit $?
fi

if [ -z "${file}" ];then
    echo "Usage: "$(basename "$0")" [wallpaper]"
    exit 1
fi

if [ ! -f "${file}" ]; then
    echo "setbg: "${file}" - No such file or directory"
    exit 1
fi

fullpath="$(readlink -f "${file}")"

feh --bg-fill "${fullpath}"
if [ "$?" -eq 0 ]; then
    echo "feh --bg-fill '${fullpath}'" > "${restfile}"
else
    exit 1
fi
